# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Address',
            new_name='address',
        ),
    ]
